#ifndef __XPLAYER_DEFINITIONS_H__
#define __XPLAYER_DEFINITIONS_H__

// 播放器状态
typedef enum _XPLAYER_STATE
{
    XPLAYER_STATE_NONE,
    XPLAYER_STATE_READY,      // 已就绪
    XPLAYER_STATE_PAUSE,      // 暂停
    XPLAYER_STATE_PLAYING,    // 播放中
    XPLAYER_STATE_OVER,       // 播放完成
    XPLAYER_STATE_ERROR,      // 播放出错
    XPLAYER_STATE_MAX
} XPLAYER_STATE;

// 播放倍速
typedef enum _XPLAYER_SPEED_MODE
{
    XPLAYER_SPEED_ONE_QUATER,  // 0.25
    XPLAYER_SPEED_ONE_HALF,    // 0.5
    XPLAYER_SPEED_NORMAL,      // 1.0
    XPLAYER_SPEED_DOUBLE,      // 2
    XPLAYER_SPEED_QUADRUPLE,   // 4倍速
} XPLAYER_SPEED_MODE;

typedef enum _XPLAYER_VIDEO_RENDERER_TYPE
{
    XPLAYER_VIDEO_RENDERER_NONE,
    XPLAYER_VIDEO_RENDERER_SDL2,
    XPLAYER_VIDEO_RENDERER_OPENGL,
    XPLAYER_VIDEO_RENDERER_MAX
} XPLAYER_VIDEO_RENDERER_TYPE;

typedef enum _XPLAYER_RECORD_MODE
{
    XPLAYER_RECORD_NONE,
    XPLAYER_RECORD_VOD,    // 点播
    XPLAYER_RECORD_LIVE,   // 直播
    XPLAYER_RECORD_MAX
} XPLAYER_RECORD_MODE;

#endif
