#ifndef __XPLAYER_DEFINITIONS_H__
#define __XPLAYER_DEFINITIONS_H__

// 播放器状态
typedef enum _XPLAYER_STATE
{
    XPLAYER_STATE_NONE,
    XPLAYER_STATE_READY,      // 已就绪
    XPLAYER_STATE_PAUSE,      // 暂停
    XPLAYER_STATE_PLAYING,    // 播放中
    XPLAYER_STATE_OVER,       // 播放完成
    XPLAYER_STATE_ERROR,      // 播放出错
    XPLAYER_STATE_MAX
} XPLAYER_STATE;

// 播放倍速
typedef enum _XPLAYER_SPEED_MODE
{
    XPLAYER_SPEED_ONE_QUATER,  // 0.25
    XPLAYER_SPEED_ONE_HALF,    // 0.5
    XPLAYER_SPEED_NORMAL,      // 1.0
    XPLAYER_SPEED_DOUBLE,      // 2
    XPLAYER_SPEED_QUADRUPLE,   // 4倍速
} XPLAYER_SPEED_MODE;

// 解码器类型
typedef enum _XPLAYER_DECODER_TYPE
{
    XPLAYER_DECODER_NONE,
    XPLAYER_DECODER_SOFTWARE,
    XPLAYER_DECODER_HARDWARE,
    XPLAYER_DECODER_MAX
} XPLAYER_DECODER_TYPE;

// 渲染器类型
typedef enum _XPLAYER_VIDEO_RENDERER_TYPE
{
    XPLAYER_VIDEO_RENDERER_NONE,
    XPLAYER_VIDEO_RENDERER_SDL2,
    XPLAYER_VIDEO_RENDERER_OPENGL,
    XPLAYER_VIDEO_RENDERER_MAX
} XPLAYER_VIDEO_RENDERER_TYPE;

// 渲染器支持的像素格式
typedef enum _XPLAYER_PIXEL_FORMAT_TYPE
{
    XPLAYER_PIXEL_FORMAT_NONE,
    XPLAYER_PIXEL_FORMAT_YUV420P,
    XPLAYER_PIXEL_FORMAT_YUY2,
    XPLAYER_PIXEL_FORMAT_UYVY,
    XPLAYER_PIXEL_FORMAT_YVYU,
    XPLAYER_PIXEL_FORMAT_YUV420P10,
    XPLAYER_PIXEL_FORMAT_NV12,
    XPLAYER_PIXEL_FORMAT_NV21,
    XPLAYER_PIXEL_FORMAT_P010,
    XPLAYER_PIXEL_FORMAT_MAX
} XPLAYER_PIXEL_FORMAT_TYPE;

// 播放记录模式
typedef enum _XPLAYER_RECORD_MODE
{
    XPLAYER_RECORD_NONE,
    XPLAYER_RECORD_VOD,    // 点播
    XPLAYER_RECORD_LIVE,   // 直播
    XPLAYER_RECORD_MAX
} XPLAYER_RECORD_MODE;

#endif
